{% set name = "xontrib-ssh-agent" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f62dc525ca05ce875c864c159b9d6abac40fd60dd01657405318d23b8f74993c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - xonsh

test:
  commands:
    - test -f "${SP_DIR}/xontrib/ssh_agent.xsh"

about:
  home: https://bitbucket.org/dyuri/xontrib-ssh-agent
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: ssh-agent xonsh integration

extra:
  recipe-maintainers:
    - scopatz
