{% set name = "xontrib-ssh-agent" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3ed5765dd763ca6081c4a9c205aa6a0a19ecb6d606416c6fa105f4cf1490f51b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - xonsh

test:
  commands:
    - test -f "${SP_DIR}/xontrib/ssh_agent.xsh"

about:
  home: https://bitbucket.org/dyuri/xontrib-ssh-agent
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: ssh-agent xonsh integration

extra:
  recipe-maintainers:
    - scopatz
