travis:
  secure:
    BINSTAR_TOKEN: FxlNnNmg2AOf1icFnwATNkvA1UlYXTg2h+vJ5KX8gFThc6Y8+ZRCSi/WPpC0w5lcPnYTsX+8iiKYPOit+RK1YJA2CODj4d6p78VQhw0P7mLpZa/FjLe/y5mc6QLQGaXmXyzMyrwpN+PUjOc1sPk6M9IBgFqF0gdM2XNudmmOe7ddclqbXKhA3avpA/Glj/7Z5kF3Sj8yar4gcrOCoSUN9k8HEfUppnf/Ln9iACzPunQVKS8YDkvB3gSa6PRqHdIfAMVOUwq0VbFIsu+59Eq8STMN06WTHRVmtABf7hFWRaZ7KxfPHSPgnbaZ/b+tcIK66nLNE6Dpvv0CKBWQPPKboTwjT0xiXkNVrBkwI513ENyluTMwR1YNpjLJ77w5FS5HRbWFZ59DvGMHOZJWVv+nqOaHTbQuxu8FXnaOQOcI3eM1O7s6Z/paf+oX9GywSSZMlcFXSVtpC10iVCpyogLIWzfUa9iq+dEenantZX9rUkSrQ4O1gdGLk3kMPquV/+cT4QwCctEMjMMhtJuo0LYwoP7lrgQUyfs4EJCYdA+aTOb2mC11Mzi1EoPkySNlNxlmWPX4mkDbt5DFfzf1F9krFwKlg1QM9KCjon0WRnhALXTCkcQuRZcVmdZ7F1ANht76oBBuFcfCzM9ruF5Y/+ur3FhybZ+8bWzUE7Wetrl3BaE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
